id: hl7.org.nz.fhir.ig.icp
canonical: http://hl7.org.nz/fhir
name: icp
title: New Zealand ICP Implementation Guide
description: This is the New Zealand ICP Implementation Guide
status: draft # draft | active | retired | unknown
version: 0.1.1
fhirVersion: 4.0.1
copyrightYear: 2023+
license: CC0-1.0
releaseLabel: ci-build # ci-build | draft | qa-preview | ballot | trial-use | release | update | normative+trial-use
publisher:
  name: Accident Compensation Corporation

parameters:
  show-inherited-invariants: false
  # apply-version: false
  generate-version: r4
  validation: [allow-any-extensions]
  excludettl: true
  excludexml: true
  
# The dependencies property corresponds to IG.dependsOn. The key is the
# package id and the value is the version (or dev/current). For advanced
# use cases, the value can be an object with keys for id, uri, and version.
#
dependencies:
  fhir.org.nz.ig.base:
     uri: 'http://fhir.org.nz/ig/base/ImplementationGuide/fhir.org.nz.ig.base'
     version: 2.1.1
pages:
  index.md:
    title: IG Home
  profiles.md:
    title: Profiles
  extensions.md:
    title: Extensions
  terminology.md:
    title: Terminology
  namingSystems.md:
    title: Naming Systems
