name: IG Build
on:
  workflow_dispatch

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    container:
      image: accnewzealand/ig-publisher:latest
      credentials:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
    permissions:
      packages: write
      contents: read  
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        
      - name: Set Java Heap Space
        run: |
          echo "export JAVA_TOOL_OPTIONS='-Xmx2g'" >> $GITHUB_ENV

      - name: Copy shell script file
        run: |
          mkdir -p /apps/icp
          cp -r * /apps/icp/
          chmod +x /apps/icp/build-publish.sh

      - name: Run shell script
        run: |
          /apps/icp/build-publish.sh

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 16 # Adjust to your Node.js version
          registry-url: https://npm.pkg.github.com/
      
      - name: Create package.json
        run: |
          cd /apps/icp/package
          echo '{
            "name": "@integration-services-accnz/icp",
            "version": "1.0.9",
            "publishConfig": {
                "registry": "https://npm.pkg.github.com"
              },
            "repository":"https://github.com/integration-services-accnz/icp",
            "canonical": "http://hl7.org.nz/fhir/icp",
            "url": "http://hl7.org.nz/fhir/icp",
            "title": "New Zealand ICP Implementation Guide",
            "description": "The ICP facade",
            "language": "en",
            "author": "ACC Integration",
            "maintainers": [
                {
                    "name": "ACC Integration",
                    "email": "integrationsupport@acc.co.nz"
                }
            ],
            "license": "CC0-1.0"
          }' > package.json
        
      - name: Publish to GitHub Package Registry
        run: |
          cd /apps/icp/package
          npm publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}

