name: IG Build

on:
  push:
    branches:
      - action-flow
jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    container:
      image: gokulmoorthi781/fsh:latest
      credentials:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Copy shell script file
        run: |
          mkdir -p /apps/icp
          cp -r * /apps/icp/
          chmod +x /apps/icp/build-publish.sh

      - name: Run shell script
        run: |
          /apps/icp/build-publish.sh

     
      - name: NPM Publish
        env:
          REGISTRY_URL: https://pkgs.dev.azure.com/accapplications/IntegrationServices/_packaging/icp-ig/npm/registry/
          USERNAME: ${{ secrets.NPM_USERNAME }}
          PAT: ${{ secrets.NPM_PASSWORD }}
          EMAIL_ADDRESS: ${{ secrets.EMAIL_ADDRESS }}
        run: |
          cd /apps/icp/package
          # Set the registry URL and authentication
          npm config set registry $REGISTRY_URL/
          npm config set //$REGISTRY_URL/:username $USERNAME
          npm config set //$REGISTRY_URL/:_password $PAT
          npm config set //$REGISTRY_URL/:email $EMAIL_ADDRESS
          npm config set //$REGISTRY_URL/:always-auth true

          # Publish the npm package
          npm publish    

      # - name: Push Docker image
      #   uses: docker/build-push-action@v2
      #   with:
      #     context: .
      #     push: true
      #     tags: myimage:latest

      # - name: Copy package.zip to another repository
      #   uses: actions/upload-artifact@v2
      #   with:
      #     name: package.zip
      #     path: /path/to/package.zip
