name: IG Build

on:
  push:
    branches:
      - action-flow
jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      - name: Build Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          dockerfile: ./Dockerfile
          push: false
          tags: icp-fhir:latest
      - name: Copy folder into Docker container
        run: docker cp ./* ${{ github.job.container.id }}:/app/icp
      - name: Run shell script in Docker container
        run: |
          docker exec ${{ github.job.container.id }} sh -c 'cd /app/icp && ./script.sh'

      - name: Run script
        run: |
          ./test.sh icp
          

      # - name: Push Docker image
      #   uses: docker/build-push-action@v2
      #   with:
      #     context: .
      #     push: true
      #     tags: myimage:latest

      - name: Copy package.zip to another repository
        uses: actions/upload-artifact@v2
        with:
          name: package.zip
          path: /path/to/package.zip