name: IG Build
on:
  workflow_dispatch

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    container:
      image: accnewzealand/ig-publisher:latest
      credentials:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Copy shell script file
        run: |
          mkdir -p /apps/icp
          cp -r * /apps/icp/
          chmod +x /apps/icp/build-publish.sh

      - name: Run shell script
        run: |
          /apps/icp/build-publish.sh

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14 # Adjust to your Node.js version
        

      - name: Authenticate with GitHub Package Registry
        run: echo "//npm.pkg.github.com/:_authToken=\${{ secrets.PACKAGE_GITHUB_TOKEN }}" > ~/.npmrc


      - name: Publish to GitHub Package Registry
        run: npm publish

      # - name: NPM Publish
      #   env:
      #     REGISTRY_URL: https://pkgs.dev.azure.com/accapplications/IntegrationServices/_packaging/Integration-Suraj/npm/registry
      #     USERNAME: ${{secrets.NPM_USERNAME}}
      #     PAT: ${{secrets.NPM_PASSWORD}}
      #     EMAIL_ADDRESS: ${{secrets.EMAIL_ADDRESS}}
      #   run: |
      #     cd /apps/icp/package         
      #     npm config --userconfig .npmrc set registry $REGISTRY_URL/
      #     npm config --userconfig .npmrc set //$REGISTRY_URL/:username $USERNAME
      #     npm config --userconfig .npmrc set //$REGISTRY_URL/:_password $PAT
      #     npm config --userconfig .npmrc set //$REGISTRY_URL/:email $EMAIL_ADDRESS
      #     npm whoami
      #     # Set the registry URL and authentication
      #      echo "//$REGISTRY_URL/:_authToken=\${{secrets.NPM_PASSWORD}}" >> ~/.npmrc
      #      npm whoami

      #     # Publish the npm package
      #     npm version $(npm view hl7.org.nz.fhir.ig.icp.r4 version)
      #     npm version prerelease
      #     npm publish

