name: IG Build

on:
  push:
    branches:
      - action-flow
jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    container:
      image: accnewzealand/ubi8:latest
      credentials:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Copy shell script file
        run: |
          mkdir -p $HOME/icp
          cp * $HOME/icp/
          chmod +x $HOME/icp/test.sh

      - name: Run shell script
        run: |
          $HOME/icp/test.sh

     
          

      # - name: Push Docker image
      #   uses: docker/build-push-action@v2
      #   with:
      #     context: .
      #     push: true
      #     tags: myimage:latest

      # - name: Copy package.zip to another repository
      #   uses: actions/upload-artifact@v2
      #   with:
      #     name: package.zip
      #     path: /path/to/package.zip
