# this mirrors all changes from the icp to the icp-mirror repository

name: mirror

# sdfsdf
on:
  workflow_dispatch:
#     branches:  [ trunk ]
    
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
     
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
        with:
          persist-credentials: true # otherwise, the token used is the GITHUB_TOKEN, instead of your personal access token.
          fetch-depth: 0 # otherwise, there would be errors pushing refs to the destination repository.
      
#         git config --local user.email "acc-fhir-publisher@acc.co.nz"
#         git config --local user.name "acc-fhir-publisher@acc.co.nz"
      - name: Configure remote and push
        run: |
          git remote set-url origin git@github.com:Garret-Besser_accnz/integration-services-accnz/icp-clone.git
          git push -u origin trunk
